/**
 * QuantumByte Technologies — Sanity Seed Script
 * Run: node scripts/seed_sanity.mjs
 *
 * Pushes all products and IT services into your Sanity dataset.
 * Requires SANITY_API_WRITE_TOKEN in .env.local
 */

import { createClient } from '@sanity/client'
import * as dotenv from 'dotenv'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { readFileSync } from 'fs'

// Load .env.local
const __dirname = dirname(fileURLToPath(import.meta.url))
const envPath = join(__dirname, '..', '.env.local')
try {
  const envContent = readFileSync(envPath, 'utf-8')
  const lines = envContent.split('\n').filter(l => l.trim() && !l.startsWith('#'))
  lines.forEach(line => {
    const [key, ...vals] = line.split('=')
    if (key && vals.length) {
      process.env[key.trim()] = vals.join('=').trim().replace(/^"|"$/g, '')
    }
  })
} catch (e) {
  console.error('Could not load .env.local:', e.message)
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: '2026-08-11',
  token: process.env.SANITY_API_WRITE_TOKEN,
  useCdn: false,
})

if (!process.env.SANITY_API_WRITE_TOKEN) {
  console.error('\n❌ SANITY_API_WRITE_TOKEN is missing in .env.local')
  console.error('   Get a write token from: https://www.sanity.io/manage → your project → API → Tokens')
  process.exit(1)
}

// ─────────────────────────────────────────────────────────
// PRODUCT DATA — 35 Products (7 per category)
// ─────────────────────────────────────────────────────────
const products = [
  // COMPUTERS ──────────────────────────────
  {
    _type: 'product',
    name: 'Apple Mac Studio M2 Ultra',
    brand: 'Apple',
    category: 'computers',
    price: 3999,
    discountPrice: 4299,
    imageUrl: '/images/computers/apple_mac_studio.jpg',
    rating: 4.9,
    reviewsCount: 48,
    stock: 8,
    isFeatured: true,
    isNewRelease: true,
    description: 'Empowered by the M2 Ultra chip, Mac Studio delivers workstation performance in a compact form factor for professional audio, video, and 3D rendering.',
    specs: ['24-Core CPU', '60-Core GPU', '64GB Unified Memory', '1TB NVMe SSD', 'Thunderbolt 4 Ports', 'macOS Sonoma'],
  },
  {
    _type: 'product',
    name: 'ASUS ROG Strix G35 Gaming Desktop',
    brand: 'ASUS',
    category: 'computers',
    price: 2899,
    discountPrice: 3199,
    imageUrl: '/images/computers/asus_rog_strix_g35.jpg',
    rating: 4.8,
    reviewsCount: 64,
    stock: 12,
    isFeatured: true,
    isNewRelease: false,
    description: 'Dominate esports with Intel Core i9 14900KF, RTX 4080 Super, and Aura Sync RGB liquid cooling inside a sleek chassis.',
    specs: ['Intel Core i9-14900KF', 'NVIDIA RTX 4080 Super 16GB', '32GB DDR5 RAM', '2TB Gen4 M.2 SSD', 'Liquid Cooled', 'Wi-Fi 7'],
  },
  {
    _type: 'product',
    name: 'Alienware Aurora R16 Gaming PC',
    brand: 'Alienware',
    category: 'computers',
    price: 2499,
    discountPrice: 2699,
    imageUrl: '/images/computers/alienware_aurora_r16.jpg',
    rating: 4.7,
    reviewsCount: 39,
    stock: 15,
    isFeatured: false,
    isNewRelease: false,
    description: 'Re-engineered Legend 3 design for superior airflow, quieter acoustics, and maximum FPS performance in competitive titles.',
    specs: ['Intel Core i7-14700F', 'NVIDIA RTX 4070 Ti Super', '32GB DDR5 XMP', '1TB NVMe SSD', 'AlienFX RGB', 'USB 3.2 Gen 2'],
  },
  {
    _type: 'product',
    name: 'HP Omen 45L Liquid Cooled Rig',
    brand: 'HP',
    category: 'computers',
    price: 2199,
    discountPrice: 2399,
    imageUrl: '/images/computers/hp_omen_45l.jpg',
    rating: 4.6,
    reviewsCount: 29,
    stock: 10,
    isFeatured: false,
    isNewRelease: false,
    description: 'Innovative Cryo Chamber isolates the liquid cooler radiator for superior CPU thermals during extended gaming sessions.',
    specs: ['AMD Ryzen 9 7900X', 'NVIDIA RTX 4070 12GB', '32GB Kingston FURY DDR5', '1TB M.2 SSD', '800W Gold PSU', 'Cryo Chamber Cooling'],
  },
  {
    _type: 'product',
    name: 'QuantumByte Cyber Workstation Pro',
    brand: 'QuantumByte',
    category: 'computers',
    price: 4999,
    discountPrice: 5499,
    imageUrl: '/images/computers/quantumbyte_custom_rig.jpg',
    rating: 5.0,
    reviewsCount: 18,
    stock: 5,
    isFeatured: true,
    isNewRelease: true,
    description: 'Handcrafted by QuantumByte engineers. Dual-loop hardline liquid cooling, custom braided cables, and overclocked selected hardware.',
    specs: ['Intel Core i9-14900KS', 'NVIDIA RTX 4090 24GB', '64GB Corsair Dominator Titanium', '4TB Gen5 SSD', 'Hardline Watercooling', '1200W Platinum PSU'],
  },
  {
    _type: 'product',
    name: 'MSI MEG Aegis Ti5 8K PC',
    brand: 'MSI',
    category: 'computers',
    price: 3499,
    discountPrice: 3799,
    imageUrl: '/images/computers/asus_rog_strix_g35.jpg',
    rating: 4.8,
    reviewsCount: 22,
    stock: 7,
    isFeatured: false,
    isNewRelease: true,
    description: 'Award-winning futuristic chassis with built-in 7-inch touchscreen dashboard, MSI Gaming Hub, and top-tier gaming hardware.',
    specs: ['Intel Core i9-14900K', 'NVIDIA RTX 4090 24GB', '64GB DDR5', '2TB NVMe + 4TB HDD', '7" Dashboard Screen', 'MSI Mystic Light'],
  },
  {
    _type: 'product',
    name: 'Mac Pro M2 Ultra Tower',
    brand: 'Apple',
    category: 'computers',
    price: 6999,
    discountPrice: 7499,
    imageUrl: '/images/computers/apple_mac_studio.jpg',
    rating: 4.9,
    reviewsCount: 31,
    stock: 4,
    isFeatured: true,
    isNewRelease: true,
    description: 'Ultimate creative beast with M2 Ultra, PCIe expansion slots, and rack-mountable form factor. Built for the world\'s most demanding creative workflows.',
    specs: ['Apple M2 Ultra Chip', '192GB Unified Memory', '8TB SSD', '6 Thunderbolt 4 Ports', 'PCIe Gen4 Expansion', 'macOS Sonoma'],
  },

  // LAPTOPS ──────────────────────────────
  {
    _type: 'product',
    name: 'Apple MacBook Pro 16" M3 Max',
    brand: 'Apple',
    category: 'laptops',
    price: 3499,
    discountPrice: 3699,
    imageUrl: '/images/laptops/apple_macbook_pro_16.jpg',
    rating: 4.9,
    reviewsCount: 112,
    stock: 20,
    isFeatured: true,
    isNewRelease: true,
    description: 'Liquid Retina XDR display with up to 22 hours battery. Built for heavy software engineering, 8K video editing, and ML workloads.',
    specs: ['Apple M3 Max Chip', '36GB Unified Memory', '1TB Superfast SSD', '16.2" Liquid Retina XDR', 'Space Black Finish', 'Thunderbolt 4 x3'],
  },
  {
    _type: 'product',
    name: 'ASUS ROG Zephyrus G16 OLED',
    brand: 'ASUS',
    category: 'laptops',
    price: 2299,
    discountPrice: 2499,
    imageUrl: '/images/laptops/asus_rog_zephyrus_g16.jpg',
    rating: 4.8,
    reviewsCount: 78,
    stock: 14,
    isFeatured: true,
    isNewRelease: false,
    description: 'Ultra-thin CNC aluminum chassis with ROG Nebula 2.5K OLED 240Hz display and NVIDIA RTX 4080 graphics laptop power.',
    specs: ['Intel Core Ultra 9 185H', 'NVIDIA RTX 4080 12GB', '32GB LPDDR5X', '1TB PCIe 4.0 SSD', '240Hz OLED Display', 'AuraSync RGB'],
  },
  {
    _type: 'product',
    name: 'Dell XPS 16 Ultra Laptop',
    brand: 'Dell',
    category: 'laptops',
    price: 1999,
    discountPrice: 2199,
    imageUrl: '/images/laptops/dell_xps_16_ultra.jpg',
    rating: 4.7,
    reviewsCount: 54,
    stock: 18,
    isFeatured: false,
    isNewRelease: false,
    description: 'Futuristic glass touchpad, capacitive touch function row, and 4K+ OLED infinity edge display for premium executive productivity.',
    specs: ['Intel Core Ultra 7 155H', 'NVIDIA RTX 4060 8GB', '32GB LPDDR5x', '1TB M.2 NVMe SSD', '16.3" 4K+ Touch OLED', 'USB4 x2'],
  },
  {
    _type: 'product',
    name: 'Lenovo Legion Pro 7i Gen 9',
    brand: 'Lenovo',
    category: 'laptops',
    price: 2599,
    discountPrice: 2799,
    imageUrl: '/images/laptops/lenovo_legion_pro_7.jpg',
    rating: 4.8,
    reviewsCount: 89,
    stock: 11,
    isFeatured: false,
    isNewRelease: false,
    description: 'AI-tuned legion Coldfront vapor chamber thermal technology with TrueStrike RGB per-key keyboard and 240Hz QHD+ display.',
    specs: ['Intel Core i9-14900HX', 'NVIDIA RTX 4080 12GB', '32GB DDR5 5600MHz', '1TB Gen4 SSD', '16" WQXGA 240Hz', 'Legion AI Engine+'],
  },
  {
    _type: 'product',
    name: 'HP Spectre x360 2-in-1 Convertible',
    brand: 'HP',
    category: 'laptops',
    price: 1599,
    discountPrice: 1749,
    imageUrl: '/images/laptops/hp_spectre_x360.jpg',
    rating: 4.6,
    reviewsCount: 41,
    stock: 22,
    isFeatured: false,
    isNewRelease: false,
    description: '360-degree hinge with bundled tilt pen, 2.8K OLED touchscreen, and AI battery optimization for mobile creators.',
    specs: ['Intel Core Ultra 7 155H', 'Intel Arc Graphics', '16GB LPDDR5x', '1TB PCIe Gen4 SSD', '14" 2.8K OLED Touch', 'Wi-Fi 6E'],
  },
  {
    _type: 'product',
    name: 'Razer Blade 16 Dual-Screen Laptop',
    brand: 'Razer',
    category: 'laptops',
    price: 2999,
    discountPrice: 3299,
    imageUrl: '/images/laptops/asus_rog_zephyrus_g16.jpg',
    rating: 4.8,
    reviewsCount: 35,
    stock: 9,
    isFeatured: true,
    isNewRelease: true,
    description: 'World-first dual UHD OLED display + FHD bottom productivity screen. Ultra-slim 18mm CNC aluminum chassis with RTX 4090 laptop GPU.',
    specs: ['Intel Core i9-14900HX', 'NVIDIA RTX 4090 16GB', '64GB LPDDR5x', '2TB PCIe Gen5 SSD', 'Dual OLED Screen', 'Per-Key Razer Chroma'],
  },

  // MOBILES ──────────────────────────────
  {
    _type: 'product',
    name: 'Apple iPhone 16 Pro Max',
    brand: 'Apple',
    category: 'mobiles',
    price: 1199,
    discountPrice: 1299,
    imageUrl: '/images/mobiles/apple_iphone_16_pro.jpg',
    rating: 4.9,
    reviewsCount: 210,
    stock: 30,
    isFeatured: true,
    isNewRelease: true,
    description: 'Grade 5 titanium enclosure, A18 Pro Bionic chip, Camera Control button, and 48MP Fusion camera with 5x Telephoto zoom.',
    specs: ['A18 Pro Chip', '256GB Storage', '6.9" Super Retina XDR', '48MP Triple Lens Camera', 'Action Button & USB-C', '5G Ready'],
  },
  {
    _type: 'product',
    name: 'Samsung Galaxy S25 Ultra 5G',
    brand: 'Samsung',
    category: 'mobiles',
    price: 1299,
    discountPrice: 1399,
    imageUrl: '/images/mobiles/samsung_galaxy_s25_ultra.jpg',
    rating: 4.9,
    reviewsCount: 175,
    stock: 25,
    isFeatured: true,
    isNewRelease: true,
    description: 'Built-in S Pen, Armor Aluminum titanium frame, Snapdragon 8 Gen 4 for Galaxy, and 200MP Quad AI camera system.',
    specs: ['Snapdragon 8 Gen 4', '12GB RAM / 512GB', '6.8" Dynamic AMOLED 2X 120Hz', '200MP Main Camera', 'Built-in S Pen', '5000mAh + 45W'],
  },
  {
    _type: 'product',
    name: 'Google Pixel 9 Pro XL',
    brand: 'Google',
    category: 'mobiles',
    price: 1099,
    discountPrice: 1199,
    imageUrl: '/images/mobiles/google_pixel_9_pro.jpg',
    rating: 4.7,
    reviewsCount: 94,
    stock: 16,
    isFeatured: false,
    isNewRelease: true,
    description: 'Tensor G4 processor with Gemini Nano AI assistant built-in, Super Actua display, and best-in-class computational photography.',
    specs: ['Google Tensor G4', '16GB RAM / 256GB', '6.8" Super Actua OLED', '50MP Triple Camera', 'Gemini AI Built-in', '7 Years OS Updates'],
  },
  {
    _type: 'product',
    name: 'OnePlus 13 Pro Hasselblad',
    brand: 'OnePlus',
    category: 'mobiles',
    price: 899,
    discountPrice: 999,
    imageUrl: '/images/mobiles/oneplus_13_pro.jpg',
    rating: 4.7,
    reviewsCount: 68,
    stock: 20,
    isFeatured: false,
    isNewRelease: true,
    description: 'Hasselblad Camera 4.0, 100W SUPERVOOC charging (0 to 100% in 25 mins), and 2K 120Hz ProXDR display.',
    specs: ['Snapdragon 8 Gen 4', '16GB RAM / 512GB', '100W Wired + 50W Wireless', '50MP Sony LYT-900', '5400mAh Battery', 'Hasselblad Color Tuning'],
  },
  {
    _type: 'product',
    name: 'Xiaomi 14 Ultra Leica Edition',
    brand: 'Xiaomi',
    category: 'mobiles',
    price: 1049,
    discountPrice: 1149,
    imageUrl: '/images/mobiles/xiaomi_14_ultra.jpg',
    rating: 4.8,
    reviewsCount: 52,
    stock: 12,
    isFeatured: false,
    isNewRelease: true,
    description: 'Quad 50MP camera system co-engineered with Leica, 1-inch main sensor with step-less variable aperture (f/1.63 - f/4.0).',
    specs: ['Snapdragon 8 Gen 3', '16GB RAM / 512GB', 'Leica Quad Camera', '6.73" WQHD+ AMOLED', '90W HyperCharge', '5000mAh Battery'],
  },
  {
    _type: 'product',
    name: 'Samsung Galaxy Z Fold 6 5G',
    brand: 'Samsung',
    category: 'mobiles',
    price: 1799,
    discountPrice: 1899,
    imageUrl: '/images/mobiles/samsung_galaxy_s25_ultra.jpg',
    rating: 4.8,
    reviewsCount: 43,
    stock: 10,
    isFeatured: true,
    isNewRelease: true,
    description: 'The ultimate foldable smartphone with 7.6" main display, Galaxy AI, and PC-level multitasking capabilities on a phone.',
    specs: ['Snapdragon 8 Gen 3', '12GB RAM / 256GB', '7.6" Main + 6.3" Cover', '50MP Triple Camera', 'Galaxy AI Features', 'Armor Aluminum Frame'],
  },
  {
    _type: 'product',
    name: 'Apple iPhone 16 Plus',
    brand: 'Apple',
    category: 'mobiles',
    price: 899,
    discountPrice: 999,
    imageUrl: '/images/mobiles/apple_iphone_16_pro.jpg',
    rating: 4.7,
    reviewsCount: 88,
    stock: 24,
    isFeatured: false,
    isNewRelease: true,
    description: 'A16 Bionic chip, 6.7-inch Super Retina XDR display, all-day battery life, Action button, and USB-C connectivity.',
    specs: ['A16 Bionic Chip', '128GB Storage', '6.7" Super Retina XDR', '48MP Dual Camera', 'Action Button', 'USB-C with USB 3'],
  },

  // CHARGERS ──────────────────────────────
  {
    _type: 'product',
    name: 'Anker Prime 100W GaN Wall Charger',
    brand: 'Anker',
    category: 'chargers',
    price: 84,
    discountPrice: 99,
    imageUrl: '/images/chargers/anker_prime_100w_gan.jpg',
    rating: 4.9,
    reviewsCount: 140,
    stock: 45,
    isFeatured: true,
    isNewRelease: false,
    description: 'Ultra-compact 3-port GaNPrime adapter for charging MacBook Pro, iPhone, and iPad simultaneously at full speed.',
    specs: ['100W Max Output', '2x USB-C + 1x USB-A', 'GaNPrime Technology', 'ActiveShield 2.0', 'Universal Voltage', 'Foldable Pins'],
  },
  {
    _type: 'product',
    name: 'Apple 70W USB-C Power Adapter',
    brand: 'Apple',
    category: 'chargers',
    price: 59,
    discountPrice: 65,
    imageUrl: '/images/chargers/apple_70w_usbc_charger.jpg',
    rating: 4.8,
    reviewsCount: 98,
    stock: 35,
    isFeatured: false,
    isNewRelease: false,
    description: 'Official Apple power adapter for fast charging MacBooks and iPad Pro at home, in the office, or on the go.',
    specs: ['70W Power Output', 'USB-C Single Port', 'Official Apple OEM', 'Compact Folding Pins', 'LED Status Indicator'],
  },
  {
    _type: 'product',
    name: 'Belkin BoostCharge Pro 3-in-1 MagSafe',
    brand: 'Belkin',
    category: 'chargers',
    price: 139,
    discountPrice: 149,
    imageUrl: '/images/chargers/belkin_boostcharge_pro.jpg',
    rating: 4.8,
    reviewsCount: 82,
    stock: 25,
    isFeatured: true,
    isNewRelease: false,
    description: 'MFi-certified 15W MagSafe wireless charging stand simultaneously charges iPhone, Apple Watch, and AirPods.',
    specs: ['15W MagSafe Wireless', '3-in-1 Simultaneous', 'Premium Metal Finish', 'LED Status Ring', 'Qi2 Compatible'],
  },
  {
    _type: 'product',
    name: 'Samsung 45W Super Fast Charging 2.0',
    brand: 'Samsung',
    category: 'chargers',
    price: 49,
    discountPrice: 55,
    imageUrl: '/images/chargers/samsung_45w_fast_charger.jpg',
    rating: 4.7,
    reviewsCount: 115,
    stock: 50,
    isFeatured: false,
    isNewRelease: false,
    description: 'Original Samsung 45W wall charger with 5A Type-C cable for Galaxy phones and tablets super fast charging.',
    specs: ['45W Max USB-C PD 3.0', 'PPS Fast Charging', 'Includes 1.8m 5A Cable', 'Over-current Protection', 'Smart Circuit Protection'],
  },
  {
    _type: 'product',
    name: 'Baseus 140W GaN5 Pro Multi-Charger',
    brand: 'Baseus',
    category: 'chargers',
    price: 79,
    discountPrice: 95,
    imageUrl: '/images/chargers/baseus_140w_gan_charger.jpg',
    rating: 4.6,
    reviewsCount: 63,
    stock: 28,
    isFeatured: false,
    isNewRelease: false,
    description: 'PD 3.1 supporting 140W high wattage for gaming laptops, power banks, and flagship smartphones simultaneously.',
    specs: ['140W PD 3.1 Output', '2x USB-C + 1x USB-A', 'Includes 240W E-Mark Cable', 'BCT Cooling Tech', 'Surge Protection'],
  },
  {
    _type: 'product',
    name: 'Ugreen Nexode Pro 160W Desktop Charger',
    brand: 'Ugreen',
    category: 'chargers',
    price: 99,
    discountPrice: 119,
    imageUrl: '/images/chargers/anker_prime_100w_gan.jpg',
    rating: 4.7,
    reviewsCount: 47,
    stock: 32,
    isFeatured: false,
    isNewRelease: true,
    description: '4-port GaN desktop charging station delivering 160W total with a visual power display showing real-time wattage output.',
    specs: ['160W Total Output', '3x USB-C + 1x USB-A', 'Digital Power Display', 'GaN II Technology', 'Active Cooling Fan', 'PPS/PD/QC Support'],
  },
  {
    _type: 'product',
    name: 'QuantumByte 65W MagSafe Wireless Pad',
    brand: 'QuantumByte',
    category: 'chargers',
    price: 69,
    discountPrice: 89,
    imageUrl: '/images/chargers/belkin_boostcharge_pro.jpg',
    rating: 4.8,
    reviewsCount: 28,
    stock: 40,
    isFeatured: true,
    isNewRelease: true,
    description: 'QuantumByte premium 15W wireless MagSafe charging pad with quantum heat dissipation technology and RGB ambient ring indicator.',
    specs: ['15W MagSafe / 10W Qi2', 'RGB Ambient Ring', 'Quantum Heat Dissipation', 'Anti-slip Leather Base', 'USB-C 65W Included Adapter'],
  },

  // PARTS & COMPONENTS ──────────────────────────────
  {
    _type: 'product',
    name: 'ASUS ROG Strix RTX 4090 OC 24GB',
    brand: 'ASUS',
    category: 'parts',
    price: 1999,
    discountPrice: 2199,
    imageUrl: '/images/parts/nvidia_rtx_4090_gpu.jpg',
    rating: 5.0,
    reviewsCount: 88,
    stock: 6,
    isFeatured: true,
    isNewRelease: false,
    description: 'Ada Lovelace architecture, 24GB GDDR6X VRAM, axial-tech triple fans, and patented vapor chamber cooling for extreme 4K gaming.',
    specs: ['NVIDIA GeForce RTX 4090', '24GB GDDR6X VRAM', '2640 MHz Boost Clock', 'PCIe 4.0 x16', 'Triple Axial-Tech Fans', 'Aura Sync RGB'],
  },
  {
    _type: 'product',
    name: 'G.Skill Trident Z5 RGB 64GB DDR5',
    brand: 'G.Skill',
    category: 'parts',
    price: 249,
    discountPrice: 279,
    imageUrl: '/images/parts/gskill_trident_ddr5_ram.jpg',
    rating: 4.9,
    reviewsCount: 104,
    stock: 30,
    isFeatured: true,
    isNewRelease: false,
    description: 'Flagship DDR5 memory designed for ultra-high performance on Intel & AMD platforms with translucent light bar.',
    specs: ['64GB Kit (2x32GB)', 'DDR5 6400MHz', 'CL32 Low Latency', 'Intel XMP 3.0', 'Aluminum Heatspreader', 'Addressable RGB'],
  },
  {
    _type: 'product',
    name: 'Samsung 990 PRO 2TB NVMe PCIe 4.0 SSD',
    brand: 'Samsung',
    category: 'parts',
    price: 179,
    discountPrice: 199,
    imageUrl: '/images/parts/samsung_990_pro_ssd.jpg',
    rating: 4.9,
    reviewsCount: 165,
    stock: 40,
    isFeatured: false,
    isNewRelease: false,
    description: 'Sequential read/write up to 7,450/6,900 MB/s. Designed for gamers, enthusiasts, and heavy workstation loads.',
    specs: ['2TB Capacity', '7,450 MB/s Read', 'Pascal In-house Controller', 'Thermal Control Coating', 'PS5 & PC Compatible', '5 Year Warranty'],
  },
  {
    _type: 'product',
    name: 'ASUS ROG Maximus Z790 Hero Motherboard',
    brand: 'ASUS',
    category: 'parts',
    price: 599,
    discountPrice: 649,
    imageUrl: '/images/parts/asus_rog_z790_motherboard.jpg',
    rating: 4.8,
    reviewsCount: 47,
    stock: 14,
    isFeatured: false,
    isNewRelease: false,
    description: 'Robust 20+1 power stages, PCIe 5.0 expansion slots, Wi-Fi 6E, dual Thunderbolt 4 ports, and Polymo lighting.',
    specs: ['LGA 1700 (Intel 14th/13th Gen)', '20+1 Power Stages (90A)', 'DDR5 Support up to 8000+', 'PCIe 5.0 M.2 + GPU Slots', 'Wi-Fi 6E & 2.5G LAN', 'Thunderbolt 4 x2'],
  },
  {
    _type: 'product',
    name: 'NZXT Kraken Elite 360 RGB Liquid Cooler',
    brand: 'NZXT',
    category: 'parts',
    price: 279,
    discountPrice: 299,
    imageUrl: '/images/parts/nzxt_kraken_liquid_cooler.jpg',
    rating: 4.8,
    reviewsCount: 56,
    stock: 18,
    isFeatured: false,
    isNewRelease: false,
    description: '2.36-inch LCD display capable of showing real-time system stats or custom animated GIFs with high-static pressure fans.',
    specs: ['360mm Radiator', '640x640 LCD Display', '3x F120 RGB Core Fans', 'Asetek 7th Gen Pump', 'CAM Software Controlled', 'Multi-Socket Bracket'],
  },
  {
    _type: 'product',
    name: 'Corsair Vengeance DDR5 32GB 5600MHz',
    brand: 'Corsair',
    category: 'parts',
    price: 119,
    discountPrice: 139,
    imageUrl: '/images/parts/gskill_trident_ddr5_ram.jpg',
    rating: 4.8,
    reviewsCount: 93,
    stock: 50,
    isFeatured: false,
    isNewRelease: false,
    description: 'Optimized for AMD EXPO and Intel XMP 3.0, with custom performance PCB and tight secondary timings for competitive gaming.',
    specs: ['32GB Kit (2x16GB)', 'DDR5 5600MHz', 'AMD EXPO + Intel XMP 3.0', 'Custom Performance PCB', 'Compact Low-Profile Heatsink', 'iCUE Compatible'],
  },
  {
    _type: 'product',
    name: 'WD Black SN850X 4TB Gen4 NVMe SSD',
    brand: 'Western Digital',
    category: 'parts',
    price: 299,
    discountPrice: 339,
    imageUrl: '/images/parts/samsung_990_pro_ssd.jpg',
    rating: 4.9,
    reviewsCount: 71,
    stock: 22,
    isFeatured: true,
    isNewRelease: true,
    description: 'Game Mode 2.0 with predictive loading technology, 7,300 MB/s read speeds, and 4TB capacity for massive game libraries.',
    specs: ['4TB Capacity', '7,300 MB/s Read', '6,600 MB/s Write', 'Game Mode 2.0', 'PS5 Compatible', 'PCIe 4.0 x4 NVMe 1.4'],
  },

  // MONITORS & DISPLAYS ──────────────────────────────
  {
    _type: 'product',
    name: 'ASUS ROG Swift PG32UCDM 4K OLED 240Hz',
    brand: 'ASUS',
    category: 'monitors',
    price: 1299,
    discountPrice: 1399,
    imageUrl: '/images/monitors/asus_rog_swift_4k_oled.jpg',
    rating: 4.9,
    reviewsCount: 52,
    stock: 12,
    isFeatured: true,
    isNewRelease: true,
    description: '32-inch 4K QD-OLED gaming monitor with 240Hz refresh rate, 0.03ms response time, custom heatsink, and Dolby Vision.',
    specs: ['32" 4K UHD QD-OLED', '240Hz Refresh Rate', '0.03ms Response Time', 'DisplayHDR True Black 400', 'KVM Switch & USB-C 90W'],
  },
  {
    _type: 'product',
    name: 'Samsung Odyssey OLED G9 49" Dual QHD Curved',
    brand: 'Samsung',
    category: 'monitors',
    price: 1599,
    discountPrice: 1799,
    imageUrl: '/images/monitors/samsung_odyssey_g9_curved.jpg',
    rating: 4.9,
    reviewsCount: 74,
    stock: 8,
    isFeatured: true,
    isNewRelease: false,
    description: '49-inch 1800R curved ultra-wide gaming display with Neo Quantum Processor Pro, 240Hz refresh rate, and 0.03ms GTG response.',
    specs: ['49" Dual QHD (5120x1440)', '240Hz Refresh Rate', '1800R Curved OLED', '0.03ms GTG Response', 'Samsung Gaming Hub'],
  },
  {
    _type: 'product',
    name: 'Apple Studio Display 27" 5K Retina',
    brand: 'Apple',
    category: 'monitors',
    price: 1599,
    discountPrice: 1699,
    imageUrl: '/images/monitors/apple_studio_display_5k.jpg',
    rating: 4.8,
    reviewsCount: 68,
    stock: 15,
    isFeatured: false,
    isNewRelease: false,
    description: '27-inch 5K Retina display with 12MP Ultra Wide camera with Center Stage, studio-quality mics, and six-speaker sound system with Spatial Audio.',
    specs: ['27" 5K Retina Display', '5120x2880 Resolution', '600 Nits Brightness', '12MP Ultra Wide Camera', '6-Speaker Spatial Audio', 'Thunderbolt 3 Up to 96W'],
  },
  {
    _type: 'product',
    name: 'LG UltraGear 34GS95QE 34" Curved OLED',
    brand: 'LG',
    category: 'monitors',
    price: 1199,
    discountPrice: 1299,
    imageUrl: '/images/monitors/lg_ultragear_34_curved.jpg',
    rating: 4.7,
    reviewsCount: 38,
    stock: 10,
    isFeatured: false,
    isNewRelease: true,
    description: '34-inch 800R curved WQHD OLED gaming monitor featuring 240Hz refresh rate, VESA DisplayHDR True Black 400, and NVIDIA G-SYNC compatibility.',
    specs: ['34" UltraWide WQHD (3440x1440)', '240Hz Refresh Rate', '800R Extreme Curve', 'VESA DisplayHDR True Black 400', 'NVIDIA G-SYNC & FreeSync'],
  },

  // GAMING ACCESSORIES ──────────────────────────────
  {
    _type: 'product',
    name: 'Razer Viper V3 Pro Wireless Gaming Mouse',
    brand: 'Razer',
    category: 'accessories',
    price: 159,
    discountPrice: 179,
    imageUrl: '/images/accessories/razer_viper_v3_pro.jpg',
    rating: 4.9,
    reviewsCount: 110,
    stock: 35,
    isFeatured: true,
    isNewRelease: true,
    description: 'Ultra-lightweight 54g esports wireless mouse with Focus Pro 35K Gen-2 Optical Sensor and 8000Hz HyperPolling rate.',
    specs: ['54g Ultra-Lightweight', 'Focus Pro 35K Optical Sensor', '8000Hz HyperPolling', '95 Hours Battery Life', 'Optical Mouse Switches Gen-3'],
  },
  {
    _type: 'product',
    name: 'Logitech G915 LIGHTSPEED Wireless Keyboard',
    brand: 'Logitech',
    category: 'accessories',
    price: 229,
    discountPrice: 249,
    imageUrl: '/images/accessories/logitech_g915_keyboard.jpg',
    rating: 4.8,
    reviewsCount: 95,
    stock: 25,
    isFeatured: false,
    isNewRelease: false,
    description: 'Low-profile mechanical switches, aircraft-grade aluminum top case, LIGHTSPEED 1ms wireless, and LIGHTSYNC RGB per-key lighting.',
    specs: ['Low Profile GL Tactile Switches', 'LIGHTSPEED 1ms Wireless', 'LIGHTSYNC RGB Per-Key', 'Aircraft-grade AL-MG Alloy', '30 Hours Battery Life'],
  },
  {
    _type: 'product',
    name: 'SteelSeries Arctis Nova Pro Wireless',
    brand: 'SteelSeries',
    category: 'accessories',
    price: 349,
    discountPrice: 379,
    imageUrl: '/images/accessories/steelseries_arctis_nova_pro.jpg',
    rating: 4.8,
    reviewsCount: 82,
    stock: 18,
    isFeatured: true,
    isNewRelease: false,
    description: 'High-Fidelity Drivers with 360° Spatial Audio, Active Noise Cancellation, wireless GameDAC Gen 2 base station, and dual battery hot-swap system.',
    specs: ['360° Spatial Audio', 'Active Noise Cancellation (ANC)', 'GameDAC Gen 2 Wireless Base', 'Dual-Battery Hot-Swap System', 'Simultaneous 2.4GHz + BT'],
  },
  {
    _type: 'product',
    name: 'Apple AirPods Max Space Black',
    brand: 'Apple',
    category: 'accessories',
    price: 549,
    discountPrice: 579,
    imageUrl: '/images/accessories/apple_airpods_max.jpg',
    rating: 4.9,
    reviewsCount: 145,
    stock: 20,
    isFeatured: false,
    isNewRelease: true,
    description: 'Apple-designed dynamic driver, Active Noise Cancellation with Transparency mode, Personalized Spatial Audio with dynamic head tracking.',
    specs: ['Apple-Designed Dynamic Driver', 'Active Noise Cancellation & Transparency', 'Personalized Spatial Audio', 'Digital Crown Control', 'USB-C Charging', '20 Hours Battery'],
  },

  // NETWORKING & STORAGE ──────────────────────────────
  {
    _type: 'product',
    name: 'ASUS ROG Rapture GT-BE98 PRO Wi-Fi 7 Router',
    brand: 'ASUS',
    category: 'networking',
    price: 799,
    discountPrice: 849,
    imageUrl: '/images/networking/asus_rog_rapture_wifi7.jpg',
    rating: 4.9,
    reviewsCount: 34,
    stock: 9,
    isFeatured: true,
    isNewRelease: true,
    description: 'Quad-band Wi-Fi 7 gaming router with up to 30,000 Mbps speeds, dual 10G ports, 320MHz channels, and multi-link operation (MLO).',
    specs: ['Quad-Band Wi-Fi 7 (Up to 30 Gbps)', 'Dual 10G Ports + Quad 2.5G Ports', '320MHz Channel Width', 'Triple-Level Game Acceleration', 'AiProtection Pro Security'],
  },
  {
    _type: 'product',
    name: 'Synology DiskStation DS923+ 4-Bay NAS',
    brand: 'Synology',
    category: 'networking',
    price: 599,
    discountPrice: 649,
    imageUrl: '/images/networking/synology_ds923_nas.jpg',
    rating: 4.8,
    reviewsCount: 61,
    stock: 14,
    isFeatured: false,
    isNewRelease: false,
    description: 'Flexible 4-bay storage solution for home offices and small business enterprises, supporting NVMe SSD caching and 10GbE network expansion.',
    specs: ['AMD Ryzen R1600 Dual-Core', '4 Bay (Expandable up to 9)', 'Dual M.2 NVMe SSD Slots', '4GB DDR4 ECC RAM', 'Synology DSM OS', '10GbE Network Slot'],
  },
  {
    _type: 'product',
    name: 'Ubiquiti UniFi Dream Machine Special Edition',
    brand: 'Ubiquiti',
    category: 'networking',
    price: 499,
    discountPrice: 549,
    imageUrl: '/images/networking/ubiquiti_unifi_udm_se.jpg',
    rating: 4.9,
    reviewsCount: 42,
    stock: 11,
    isFeatured: true,
    isNewRelease: false,
    description: 'All-in-one enterprise console with integrated 2.5G WAN, 8-port PoE switch, 10G SFP+ interfaces, and 128GB SSD storage for UniFi application suite.',
    specs: ['Integrated 8-Port PoE/PoE+ Switch', '2.5G RJ45 + 10G SFP+ Ports', 'Integrated 3.5" HDD Bay for NVR', '1.7 GHz Quad-Core CPU', 'UniFi OS Application Suite'],
  },
]

// ─────────────────────────────────────────────────────────
// IT SERVICES DATA
// ─────────────────────────────────────────────────────────
const itServices = [
  {
    _type: 'itService',
    title: 'Custom Gaming & Workstation PC Assembly',
    subtitle: 'Professional assembly, custom liquid loop tubing, cable management & stress testing',
    imageUrl: '/images/services/custom_pc_building.jpg',
    priceStarting: 99,
    popularBadge: true,
    features: [
      'Handcrafted Component Installation & Cable Routing',
      'BIOS Flashing & XMP/EXPO Memory Tuning',
      'Stress Testing & Thermal Benchmarking (24 Hours)',
      'Custom Hardline or Softline Water Cooling Loops',
      'Official QuantumByte 1-Year Build Warranty',
    ],
    description: 'Our expert hardware engineers build your dream rig with surgical precision, immaculate cable routing, and optimal airflow.',
  },
  {
    _type: 'itService',
    title: 'Hardware Maintenance & Chip-Level Repair',
    subtitle: 'Diagnose and fix laptops, desktops, GPUs, motherboards & mobile devices',
    imageUrl: '/images/services/hardware_repair.jpg',
    priceStarting: 49,
    popularBadge: false,
    features: [
      'Motherboard BGA Reballing & Micro-soldering',
      'Laptop Screen, Battery & Keyboard Replacement',
      'Liquid Damage Cleaning & Ultrasonic Bathing',
      'GPU Thermal Paste & Pad Replacement (Honeywell PTM7950)',
      'Component-level Short Circuit Diagnostics',
    ],
    description: 'Our lab uses advanced diagnostic scopes to repair micro-electronics and save your valuable hardware from the bin.',
  },
  {
    _type: 'itService',
    title: 'Corporate IT Infrastructure & Networking',
    subtitle: 'Enterprise server setup, Wi-Fi 6E mesh coverage, NAS storage & security',
    imageUrl: '/images/services/network_infrastructure.jpg',
    priceStarting: 299,
    popularBadge: true,
    features: [
      'Structured Cat6A / Fiber Optic Cabling',
      'Synology / QNAP Enterprise NAS Backup Systems',
      'Cisco / Ubiquiti UniFi Router & Firewall Setup',
      'Active Directory, VPN & Cloud Migration',
      '24/7 Managed IT Support & SLA Contracts',
    ],
    description: 'Scale your infrastructure with secure, high-speed networking solutions designed for zero downtime and robust data backup.',
  },
  {
    _type: 'itService',
    title: 'Full-Stack Web & Mobile App Development',
    subtitle: 'Custom e-commerce platforms, SaaS web apps, iOS & Android applications',
    imageUrl: '/images/services/software_web_dev.jpg',
    priceStarting: 799,
    popularBadge: false,
    features: [
      'Modern Next.js 16, React, & Node.js Applications',
      'Sanity CMS & Headless Backend Architecture',
      'Stripe, PayPal & Custom Payment Gateway Integration',
      'UI/UX Design with GSAP Motion & Micro-interactions',
      'SEO Optimization & 99+ Lighthouse Speed Score',
    ],
    description: 'Transform your digital vision into high-converting, lightning-fast web applications built by senior engineering teams.',
  },
]

// ─────────────────────────────────────────────────────────
// RUN SEEDING
// ─────────────────────────────────────────────────────────
async function deleteExisting(type) {
  console.log(`🗑️  Deleting existing ${type} documents...`)
  const existing = await client.fetch(`*[_type == "${type}"]._id`)
  if (existing.length > 0) {
    const transaction = client.transaction()
    existing.forEach(id => transaction.delete(id))
    await transaction.commit()
    console.log(`   Deleted ${existing.length} existing ${type} documents.`)
  }
}

async function seedDocuments(docs, label) {
  console.log(`\n📦 Seeding ${docs.length} ${label}...`)
  let count = 0
  for (const doc of docs) {
    await client.create(doc)
    count++
    process.stdout.write(`   ✓ ${count}/${docs.length} — ${doc.name || doc.title}\n`)
  }
}

async function main() {
  console.log('\n🚀 QuantumByte Technologies — Sanity Seed Script')
  console.log(`   Project: ${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}`)
  console.log(`   Dataset: ${process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'}\n`)

  await deleteExisting('product')
  await deleteExisting('itService')

  await seedDocuments(products, 'products')
  await seedDocuments(itServices, 'IT services')

  console.log(`\n✅ Seeding complete! ${products.length} products + ${itServices.length} IT services added to Sanity.`)
  console.log('   Visit your Sanity Studio at http://localhost:3000/studio to verify.\n')
}

main().catch(err => {
  console.error('\n❌ Seed failed:', err.message)
  process.exit(1)
})
