/**
 * QuantumByte Technologies — Sanity Seed Script
 * Run: node scripts/seed_sanity.mjs
 *
 * Pushes all products and IT services into your Sanity dataset.
 * Requires SANITY_API_WRITE_TOKEN in .env.local
 */

import { createClient } from '@sanity/client'
import * as dotenv from 'dotenv'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { readFileSync } from 'fs'

// Load .env.local
const __dirname = dirname(fileURLToPath(import.meta.url))
const envPath = join(__dirname, '..', '.env.local')
try {
  const envContent = readFileSync(envPath, 'utf-8')
  const lines = envContent.split('\n').filter(l => l.trim() && !l.startsWith('#'))
  lines.forEach(line => {
    const [key, ...vals] = line.split('=')
    if (key && vals.length) {
      process.env[key.trim()] = vals.join('=').trim().replace(/^"|"$/g, '')
    }
  })
} catch (e) {
  console.error('Could not load .env.local:', e.message)
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: '2026-08-11',
  token: process.env.SANITY_API_WRITE_TOKEN,
  useCdn: false,
})

if (!process.env.SANITY_API_WRITE_TOKEN) {
  console.error('\n❌ SANITY_API_WRITE_TOKEN is missing in .env.local')
  console.error('   Get a write token from: https://www.sanity.io/manage → your project → API → Tokens')
  process.exit(1)
}

// ─────────────────────────────────────────────────────────
// PRODUCT DATA — 35 Products (7 per category)
// ─────────────────────────────────────────────────────────
const products = [
  // COMPUTERS ──────────────────────────────
  {
    _type: 'product',
    name: 'Apple Mac Studio M2 Ultra',
    brand: 'Apple',
    category: 'computers',
price: 999,
discountPrice: 1049,
    imageUrl: '/images/computers/apple_mac_studio.jpg',
    rating: 4.9,
    reviewsCount: 48,
    stock: 8,
    isFeatured: true,
    isNewRelease: true,
    description: 'Empowered by the M2 Ultra chip, Mac Studio delivers workstation performance in a compact form factor for professional audio, video, and 3D rendering.',
    specs: ['24-Core CPU', '60-Core GPU', '64GB Unified Memory', '1TB NVMe SSD', 'Thunderbolt 4 Ports', 'macOS Sonoma'],
  },
  {
    _type: 'product',
    name: 'ASUS ROG Strix G35 Gaming Desktop',
    brand: 'ASUS',
    category: 'computers',
price: 899,
discountPrice: 949,
    imageUrl: '/images/computers/asus_rog_strix_g35.jpg',
    rating: 4.8,
    reviewsCount: 64,
    stock: 12,
    isFeatured: true,
    isNewRelease: false,
    description: 'Dominate esports with Intel Core i9 14900KF, RTX 4080 Super, and Aura Sync RGB liquid cooling inside a sleek chassis.',
    specs: ['Intel Core i9-14900KF', 'NVIDIA RTX 4080 Super 16GB', '32GB DDR5 RAM', '2TB Gen4 M.2 SSD', 'Liquid Cooled', 'Wi-Fi 7'],
  },
  {
    _type: 'product',
    name: 'Alienware Aurora R16 Gaming PC',
    brand: 'Alienware',
    category: 'computers',
price: 849,
discountPrice: 899,
    imageUrl: '/images/computers/alienware_aurora_r16.jpg',
    rating: 4.7,
    reviewsCount: 39,
    stock: 15,
    isFeatured: false,
    isNewRelease: false,
    description: 'Re-engineered Legend 3 design for superior airflow, quieter acoustics, and maximum FPS performance in competitive titles.',
    specs: ['Intel Core i7-14700F', 'NVIDIA RTX 4070 Ti Super', '32GB DDR5 XMP', '1TB NVMe SSD', 'AlienFX RGB', 'USB 3.2 Gen 2'],
  },
  {
    _type: 'product',
    name: 'HP Omen 45L Liquid Cooled Rig',
    brand: 'HP',
    category: 'computers',
price: 799,
discountPrice: 849,
    imageUrl: '/images/computers/hp_omen_45l.jpg',
    rating: 4.6,
    reviewsCount: 29,
    stock: 10,
    isFeatured: false,
    isNewRelease: false,
    description: 'Innovative Cryo Chamber isolates the liquid cooler radiator for superior CPU thermals during extended gaming sessions.',
    specs: ['AMD Ryzen 9 7900X', 'NVIDIA RTX 4070 12GB', '32GB Kingston FURY DDR5', '1TB M.2 SSD', '800W Gold PSU', 'Cryo Chamber Cooling'],
  },
  {
    _type: 'product',
    name: 'QuantumByte Cyber Workstation Pro',
    brand: 'QuantumByte',
    category: 'computers',
price: 1049,
discountPrice: 1075.27,
    imageUrl: '/images/computers/quantumbyte_custom_rig.jpg',
    rating: 5.0,
    reviewsCount: 18,
    stock: 5,
    isFeatured: true,
    isNewRelease: true,
    description: 'Handcrafted by QuantumByte engineers. Dual-loop hardline liquid cooling, custom braided cables, and overclocked selected hardware.',
    specs: ['Intel Core i9-14900KS', 'NVIDIA RTX 4090 24GB', '64GB Corsair Dominator Titanium', '4TB Gen5 SSD', 'Hardline Watercooling', '1200W Platinum PSU'],
  },
  {
    _type: 'product',
    name: 'MSI MEG Aegis Ti5 8K PC',
    brand: 'MSI',
    category: 'computers',
price: 949,
discountPrice: 999,
    imageUrl: '/images/computers/asus_rog_strix_g35.jpg',
    rating: 4.8,
    reviewsCount: 22,
    stock: 7,
    isFeatured: false,
    isNewRelease: true,
    description: 'Award-winning futuristic chassis with built-in 7-inch touchscreen dashboard, MSI Gaming Hub, and top-tier gaming hardware.',
    specs: ['Intel Core i9-14900K', 'NVIDIA RTX 4090 24GB', '64GB DDR5', '2TB NVMe + 4TB HDD', '7" Dashboard Screen', 'MSI Mystic Light'],
  },
  {
    _type: 'product',
    name: 'Mac Pro M2 Ultra Tower',
    brand: 'Apple',
    category: 'computers',
price: 1075.27,
discountPrice: 1075.27,
    imageUrl: '/images/computers/apple_mac_studio.jpg',
    rating: 4.9,
    reviewsCount: 31,
    stock: 4,
    isFeatured: true,
    isNewRelease: true,
    description: 'Ultimate creative beast with M2 Ultra, PCIe expansion slots, and rack-mountable form factor. Built for the world\'s most demanding creative workflows.',
    specs: ['Apple M2 Ultra Chip', '192GB Unified Memory', '8TB SSD', '6 Thunderbolt 4 Ports', 'PCIe Gen4 Expansion', 'macOS Sonoma'],
  },

  // LAPTOPS ──────────────────────────────
  {
    _type: 'product',
    name: 'Apple MacBook Pro 16" M3 Max',
    brand: 'Apple',
    category: 'laptops',
price: 949,
discountPrice: 999,
    imageUrl: '/images/laptops/apple_macbook_pro_16.jpg',
    rating: 4.9,
    reviewsCount: 112,
    stock: 20,
    isFeatured: true,
    isNewRelease: true,
    description: 'Liquid Retina XDR display with up to 22 hours battery. Built for heavy software engineering, 8K video editing, and ML workloads.',
    specs: ['Apple M3 Max Chip', '36GB Unified Memory', '1TB Superfast SSD', '16.2" Liquid Retina XDR', 'Space Black Finish', 'Thunderbolt 4 x3'],
  },
  {
    _type: 'product',
    name: 'ASUS ROG Zephyrus G16 OLED',
    brand: 'ASUS',
    category: 'laptops',
price: 749,
discountPrice: 799,
    imageUrl: '/images/laptops/asus_rog_zephyrus_g16.jpg',
    rating: 4.8,
    reviewsCount: 78,
    stock: 14,
    isFeatured: true,
    isNewRelease: false,
    description: 'Ultra-thin CNC aluminum chassis with ROG Nebula 2.5K OLED 240Hz display and NVIDIA RTX 4080 graphics laptop power.',
    specs: ['Intel Core Ultra 9 185H', 'NVIDIA RTX 4080 12GB', '32GB LPDDR5X', '1TB PCIe 4.0 SSD', '240Hz OLED Display', 'AuraSync RGB'],
  },
  {
    _type: 'product',
    name: 'Dell XPS 16 Ultra Laptop',
    brand: 'Dell',
    category: 'laptops',
price: 699,
discountPrice: 749,
    imageUrl: '/images/laptops/dell_xps_16_ultra.jpg',
    rating: 4.7,
    reviewsCount: 54,
    stock: 18,
    isFeatured: false,
    isNewRelease: false,
    description: 'Futuristic glass touchpad, capacitive touch function row, and 4K+ OLED infinity edge display for premium executive productivity.',
    specs: ['Intel Core Ultra 7 155H', 'NVIDIA RTX 4060 8GB', '32GB LPDDR5x', '1TB M.2 NVMe SSD', '16.3" 4K+ Touch OLED', 'USB4 x2'],
  },
  {
    _type: 'product',
    name: 'Lenovo Legion Pro 7i Gen 9',
    brand: 'Lenovo',
    category: 'laptops',
price: 799,
discountPrice: 849,
    imageUrl: '/images/laptops/lenovo_legion_pro_7.jpg',
    rating: 4.8,
    reviewsCount: 89,
    stock: 11,
    isFeatured: false,
    isNewRelease: false,
    description: 'AI-tuned legion Coldfront vapor chamber thermal technology with TrueStrike RGB per-key keyboard and 240Hz QHD+ display.',
    specs: ['Intel Core i9-14900HX', 'NVIDIA RTX 4080 12GB', '32GB DDR5 5600MHz', '1TB Gen4 SSD', '16" WQXGA 240Hz', 'Legion AI Engine+'],
  },
  {
    _type: 'product',
    name: 'HP Spectre x360 2-in-1 Convertible',
    brand: 'HP',
    category: 'laptops',
price: 649,
discountPrice: 699,
    imageUrl: '/images/laptops/hp_spectre_x360.jpg',
    rating: 4.6,
    reviewsCount: 41,
    stock: 22,
    isFeatured: false,
    isNewRelease: false,
    description: '360-degree hinge with bundled tilt pen, 2.8K OLED touchscreen, and AI battery optimization for mobile creators.',
    specs: ['Intel Core Ultra 7 155H', 'Intel Arc Graphics', '16GB LPDDR5x', '1TB PCIe Gen4 SSD', '14" 2.8K OLED Touch', 'Wi-Fi 6E'],
  },
  {
    _type: 'product',
    name: 'Razer Blade 16 Dual-Screen Laptop',
    brand: 'Razer',
    category: 'laptops',
price: 849,
discountPrice: 899,
    imageUrl: '/images/laptops/asus_rog_zephyrus_g16.jpg',
    rating: 4.8,
    reviewsCount: 35,
    stock: 9,
    isFeatured: true,
    isNewRelease: true,
    description: 'World-first dual UHD OLED display + FHD bottom productivity screen. Ultra-slim 18mm CNC aluminum chassis with RTX 4090 laptop GPU.',
    specs: ['Intel Core i9-14900HX', 'NVIDIA RTX 4090 16GB', '64GB LPDDR5x', '2TB PCIe Gen5 SSD', 'Dual OLED Screen', 'Per-Key Razer Chroma'],
  },

  // MOBILES ──────────────────────────────
  {
    _type: 'product',
    name: 'Apple iPhone 16 Pro Max',
    brand: 'Apple',
    category: 'mobiles',
price: 599,
discountPrice: 649,
    imageUrl: '/images/mobiles/apple_iphone_16_pro.jpg',
    rating: 4.9,
    reviewsCount: 210,
    stock: 30,
    isFeatured: true,
    isNewRelease: true,
    description: 'Grade 5 titanium enclosure, A18 Pro Bionic chip, Camera Control button, and 48MP Fusion camera with 5x Telephoto zoom.',
    specs: ['A18 Pro Chip', '256GB Storage', '6.9" Super Retina XDR', '48MP Triple Lens Camera', 'Action Button & USB-C', '5G Ready'],
  },
  {
    _type: 'product',
    name: 'Samsung Galaxy S25 Ultra 5G',
    brand: 'Samsung',
    category: 'mobiles',
price: 579,
discountPrice: 619,
    imageUrl: '/images/mobiles/samsung_galaxy_s25_ultra.jpg',
    rating: 4.9,
    reviewsCount: 175,
    stock: 25,
    isFeatured: true,
    isNewRelease: true,
    description: 'Built-in S Pen, Armor Aluminum titanium frame, Snapdragon 8 Gen 4 for Galaxy, and 200MP Quad AI camera system.',
    specs: ['Snapdragon 8 Gen 4', '12GB RAM / 512GB', '6.8" Dynamic AMOLED 2X 120Hz', '200MP Main Camera', 'Built-in S Pen', '5000mAh + 45W'],
  },
  {
    _type: 'product',
    name: 'Google Pixel 9 Pro XL',
    brand: 'Google',
    category: 'mobiles',
price: 549,
discountPrice: 599,
    imageUrl: '/images/mobiles/google_pixel_9_pro.jpg',
    rating: 4.7,
    reviewsCount: 94,
    stock: 16,
    isFeatured: false,
    isNewRelease: true,
    description: 'Tensor G4 processor with Gemini Nano AI assistant built-in, Super Actua display, and best-in-class computational photography.',
    specs: ['Google Tensor G4', '16GB RAM / 256GB', '6.8" Super Actua OLED', '50MP Triple Camera', 'Gemini AI Built-in', '7 Years OS Updates'],
  },
  {
    _type: 'product',
    name: 'OnePlus 13 Pro Hasselblad',
    brand: 'OnePlus',
    category: 'mobiles',
    price: 899,
    discountPrice: 999,
    imageUrl: '/images/mobiles/oneplus_13_pro.jpg',
    rating: 4.7,
    reviewsCount: 68,
    stock: 20,
    isFeatured: false,
    isNewRelease: true,
    description: 'Hasselblad Camera 4.0, 100W SUPERVOOC charging (0 to 100% in 25 mins), and 2K 120Hz ProXDR display.',
    specs: ['Snapdragon 8 Gen 4', '16GB RAM / 512GB', '100W Wired + 50W Wireless', '50MP Sony LYT-900', '5400mAh Battery', 'Hasselblad Color Tuning'],
  },
  {
    _type: 'product',
    name: 'Xiaomi 14 Ultra Leica Edition',
    brand: 'Xiaomi',
    category: 'mobiles',
    price: 1049,
    discountPrice: 1149,
    imageUrl: '/images/mobiles/xiaomi_14_ultra.jpg',
    rating: 4.8,
    reviewsCount: 52,
    stock: 12,
    isFeatured: false,
    isNewRelease: true,
    description: 'Quad 50MP camera system co-engineered with Leica, 1-inch main sensor with step-less variable aperture (f/1.63 - f/4.0).',
    specs: ['Snapdragon 8 Gen 3', '16GB RAM / 512GB', 'Leica Quad Camera', '6.73" WQHD+ AMOLED', '90W HyperCharge', '5000mAh Battery'],
  },
  {
    _type: 'product',
    name: 'Samsung Galaxy Z Fold 6 5G',
    brand: 'Samsung',
    category: 'mobiles',
price: 649,
discountPrice: 699,
    imageUrl: '/images/mobiles/samsung_galaxy_s25_ultra.jpg',
    rating: 4.8,
    reviewsCount: 43,
    stock: 10,
    isFeatured: true,
    isNewRelease: true,
    description: 'The ultimate foldable smartphone with 7.6" main display, Galaxy AI, and PC-level multitasking capabilities on a phone.',
    specs: ['Snapdragon 8 Gen 3', '12GB RAM / 256GB', '7.6" Main + 6.3" Cover', '50MP Triple Camera', 'Galaxy AI Features', 'Armor Aluminum Frame'],
  },
  {
    _type: 'product',
    name: 'Apple iPhone 16 Plus',
    brand: 'Apple',
    category: 'mobiles',
    price: 899,
    discountPrice: 999,
    imageUrl: '/images/mobiles/apple_iphone_16_pro.jpg',
    rating: 4.7,
    reviewsCount: 88,
    stock: 24,
    isFeatured: false,
    isNewRelease: true,
    description: 'A16 Bionic chip, 6.7-inch Super Retina XDR display, all-day battery life, Action button, and USB-C connectivity.',
    specs: ['A16 Bionic Chip', '128GB Storage', '6.7" Super Retina XDR', '48MP Dual Camera', 'Action Button', 'USB-C with USB 3'],
  },

  // CHARGERS ──────────────────────────────
  {
    _type: 'product',
    name: 'Anker Prime 100W GaN Wall Charger',
    brand: 'Anker',
    category: 'chargers',
    price: 84,
    discountPrice: 99,
    imageUrl: '/images/chargers/anker_prime_100w_gan.jpg',
    rating: 4.9,
    reviewsCount: 140,
    stock: 45,
    isFeatured: true,
    isNewRelease: false,
    description: 'Ultra-compact 3-port GaNPrime adapter for charging MacBook Pro, iPhone, and iPad simultaneously at full speed.',
    specs: ['100W Max Output', '2x USB-C + 1x USB-A', 'GaNPrime Technology', 'ActiveShield 2.0', 'Universal Voltage', 'Foldable Pins'],
  },
  {
    _type: 'product',
    name: 'Apple 70W USB-C Power Adapter',
    brand: 'Apple',
    category: 'chargers',
    price: 59,
    discountPrice: 65,
    imageUrl: '/images/chargers/apple_70w_usbc_charger.jpg',
    rating: 4.8,
    reviewsCount: 98,
    stock: 35,
    isFeatured: false,
    isNewRelease: false,
    description: 'Official Apple power adapter for fast charging MacBooks and iPad Pro at home, in the office, or on the go.',
    specs: ['70W Power Output', 'USB-C Single Port', 'Official Apple OEM', 'Compact Folding Pins', 'LED Status Indicator'],
  },
  {
    _type: 'product',
    name: 'Belkin BoostCharge Pro 3-in-1 MagSafe',
    brand: 'Belkin',
    category: 'chargers',
    price: 139,
    discountPrice: 149,
    imageUrl: '/images/chargers/belkin_boostcharge_pro.jpg',
    rating: 4.8,
    reviewsCount: 82,
    stock: 25,
    isFeatured: true,
    isNewRelease: false,
    description: 'MFi-certified 15W MagSafe wireless charging stand simultaneously charges iPhone, Apple Watch, and AirPods.',
    specs: ['15W MagSafe Wireless', '3-in-1 Simultaneous', 'Premium Metal Finish', 'LED Status Ring', 'Qi2 Compatible'],
  },
  {
    _type: 'product',
    name: 'Samsung 45W Super Fast Charging 2.0',
    brand: 'Samsung',
    category: 'chargers',
    price: 49,
    discountPrice: 55,
    imageUrl: '/images/chargers/samsung_45w_fast_charger.jpg',
    rating: 4.7,
    reviewsCount: 115,
    stock: 50,
    isFeatured: false,
    isNewRelease: false,
    description: 'Original Samsung 45W wall charger with 5A Type-C cable for Galaxy phones and tablets super fast charging.',
    specs: ['45W Max USB-C PD 3.0', 'PPS Fast Charging', 'Includes 1.8m 5A Cable', 'Over-current Protection', 'Smart Circuit Protection'],
  },
  {
    _type: 'product',
    name: 'Baseus 140W GaN5 Pro Multi-Charger',
    brand: 'Baseus',
    category: 'chargers',
    price: 79,
    discountPrice: 95,
    imageUrl: '/images/chargers/baseus_140w_gan_charger.jpg',
    rating: 4.6,
    reviewsCount: 63,
    stock: 28,
    isFeatured: false,
    isNewRelease: false,
    description: 'PD 3.1 supporting 140W high wattage for gaming laptops, power banks, and flagship smartphones simultaneously.',
    specs: ['140W PD 3.1 Output', '2x USB-C + 1x USB-A', 'Includes 240W E-Mark Cable', 'BCT Cooling Tech', 'Surge Protection'],
  },
  {
    _type: 'product',
    name: 'Ugreen Nexode Pro 160W Desktop Charger',
    brand: 'Ugreen',
    category: 'chargers',
    price: 99,
    discountPrice: 119,
    imageUrl: '/images/chargers/anker_prime_100w_gan.jpg',
    rating: 4.7,
    reviewsCount: 47,
    stock: 32,
    isFeatured: false,
    isNewRelease: true,
    description: '4-port GaN desktop charging station delivering 160W total with a visual power display showing real-time wattage output.',
    specs: ['160W Total Output', '3x USB-C + 1x USB-A', 'Digital Power Display', 'GaN II Technology', 'Active Cooling Fan', 'PPS/PD/QC Support'],
  },
  {
    _type: 'product',
    name: 'QuantumByte 65W MagSafe Wireless Pad',
    brand: 'QuantumByte',
    category: 'chargers',
    price: 69,
    discountPrice: 89,
    imageUrl: '/images/chargers/belkin_boostcharge_pro.jpg',
    rating: 4.8,
    reviewsCount: 28,
    stock: 40,
    isFeatured: true,
    isNewRelease: true,
    description: 'QuantumByte premium 15W wireless MagSafe charging pad with quantum heat dissipation technology and RGB ambient ring indicator.',
    specs: ['15W MagSafe / 10W Qi2', 'RGB Ambient Ring', 'Quantum Heat Dissipation', 'Anti-slip Leather Base', 'USB-C 65W Included Adapter'],
  },

  // PARTS & COMPONENTS ──────────────────────────────
  {
    _type: 'product',
    name: 'ASUS ROG Strix RTX 4090 OC 24GB',
    brand: 'ASUS',
    category: 'parts',
price: 949,
discountPrice: 999,
    imageUrl: '/images/parts/nvidia_rtx_4090_gpu.jpg',
    rating: 5.0,
    reviewsCount: 88,
    stock: 6,
    isFeatured: true,
    isNewRelease: false,
    description: 'Ada Lovelace architecture, 24GB GDDR6X VRAM, axial-tech triple fans, and patented vapor chamber cooling for extreme 4K gaming.',
    specs: ['NVIDIA GeForce RTX 4090', '24GB GDDR6X VRAM', '2640 MHz Boost Clock', 'PCIe 4.0 x16', 'Triple Axial-Tech Fans', 'Aura Sync RGB'],
  },
  {
    _type: 'product',
    name: 'G.Skill Trident Z5 RGB 64GB DDR5',
    brand: 'G.Skill',
    category: 'parts',
    price: 249,
    discountPrice: 279,
    imageUrl: '/images/parts/gskill_trident_ddr5_ram.jpg',
    rating: 4.9,
    reviewsCount: 104,
    stock: 30,
    isFeatured: true,
    isNewRelease: false,
    description: 'Flagship DDR5 memory designed for ultra-high performance on Intel & AMD platforms with translucent light bar.',
    specs: ['64GB Kit (2x32GB)', 'DDR5 6400MHz', 'CL32 Low Latency', 'Intel XMP 3.0', 'Aluminum Heatspreader', 'Addressable RGB'],
  },
  {
    _type: 'product',
    name: 'Samsung 990 PRO 2TB NVMe PCIe 4.0 SSD',
    brand: 'Samsung',
    category: 'parts',
    price: 179,
    discountPrice: 199,
    imageUrl: '/images/parts/samsung_990_pro_ssd.jpg',
    rating: 4.9,
    reviewsCount: 165,
    stock: 40,
    isFeatured: false,
    isNewRelease: false,
    description: 'Sequential read/write up to 7,450/6,900 MB/s. Designed for gamers, enthusiasts, and heavy workstation loads.',
    specs: ['2TB Capacity', '7,450 MB/s Read', 'Pascal In-house Controller', 'Thermal Control Coating', 'PS5 & PC Compatible', '5 Year Warranty'],
  },
  {
    _type: 'product',
    name: 'ASUS ROG Maximus Z790 Hero Motherboard',
    brand: 'ASUS',
    category: 'parts',
    price: 599,
    discountPrice: 649,
    imageUrl: '/images/parts/asus_rog_z790_motherboard.jpg',
    rating: 4.8,
    reviewsCount: 47,
    stock: 14,
    isFeatured: false,
    isNewRelease: false,
    description: 'Robust 20+1 power stages, PCIe 5.0 expansion slots, Wi-Fi 6E, dual Thunderbolt 4 ports, and Polymo lighting.',
    specs: ['LGA 1700 (Intel 14th/13th Gen)', '20+1 Power Stages (90A)', 'DDR5 Support up to 8000+', 'PCIe 5.0 M.2 + GPU Slots', 'Wi-Fi 6E & 2.5G LAN', 'Thunderbolt 4 x2'],
  },
  {
    _type: 'product',
    name: 'NZXT Kraken Elite 360 RGB Liquid Cooler',
    brand: 'NZXT',
    category: 'parts',
    price: 279,
    discountPrice: 299,
    imageUrl: '/images/parts/nzxt_kraken_liquid_cooler.jpg',
    rating: 4.8,
    reviewsCount: 56,
    stock: 18,
    isFeatured: false,
    isNewRelease: false,
    description: '2.36-inch LCD display capable of showing real-time system stats or custom animated GIFs with high-static pressure fans.',
    specs: ['360mm Radiator', '640x640 LCD Display', '3x F120 RGB Core Fans', 'Asetek 7th Gen Pump', 'CAM Software Controlled', 'Multi-Socket Bracket'],
  },
  {
    _type: 'product',
    name: 'Corsair Vengeance DDR5 32GB 5600MHz',
    brand: 'Corsair',
    category: 'parts',
    price: 119,
    discountPrice: 139,
    imageUrl: '/images/parts/gskill_trident_ddr5_ram.jpg',
    rating: 4.8,
    reviewsCount: 93,
    stock: 50,
    isFeatured: false,
    isNewRelease: false,
    description: 'Optimized for AMD EXPO and Intel XMP 3.0, with custom performance PCB and tight secondary timings for competitive gaming.',
    specs: ['32GB Kit (2x16GB)', 'DDR5 5600MHz', 'AMD EXPO + Intel XMP 3.0', 'Custom Performance PCB', 'Compact Low-Profile Heatsink', 'iCUE Compatible'],
  },
  {
    _type: 'product',
    name: 'WD Black SN850X 4TB Gen4 NVMe SSD',
    brand: 'Western Digital',
    category: 'parts',
    price: 299,
    discountPrice: 339,
    imageUrl: '/images/parts/samsung_990_pro_ssd.jpg',
    rating: 4.9,
    reviewsCount: 71,
    stock: 22,
    isFeatured: true,
    isNewRelease: true,
    description: 'Game Mode 2.0 with predictive loading technology, 7,300 MB/s read speeds, and 4TB capacity for massive game libraries.',
    specs: ['4TB Capacity', '7,300 MB/s Read', '6,600 MB/s Write', 'Game Mode 2.0', 'PS5 Compatible', 'PCIe 4.0 x4 NVMe 1.4'],
  },

  // MONITORS & DISPLAYS ──────────────────────────────
  {
    _type: 'product',
    name: 'ASUS ROG Swift PG32UCDM 4K OLED 240Hz',
    brand: 'ASUS',
    category: 'monitors',
price: 799,
discountPrice: 849,
    imageUrl: '/images/monitors/asus_rog_swift_4k_oled.jpg',
    rating: 4.9,
    reviewsCount: 52,
    stock: 12,
    isFeatured: true,
    isNewRelease: true,
    description: '32-inch 4K QD-OLED gaming monitor with 240Hz refresh rate, 0.03ms response time, custom heatsink, and Dolby Vision.',
    specs: ['32" 4K UHD QD-OLED', '240Hz Refresh Rate', '0.03ms Response Time', 'DisplayHDR True Black 400', 'KVM Switch & USB-C 90W'],
  },
  {
    _type: 'product',
    name: 'Samsung Odyssey OLED G9 49" Dual QHD Curved',
    brand: 'Samsung',
    category: 'monitors',
price: 849,
discountPrice: 899,
    imageUrl: '/images/monitors/samsung_odyssey_g9_curved.jpg',
    rating: 4.9,
    reviewsCount: 74,
    stock: 8,
    isFeatured: true,
    isNewRelease: false,
    description: '49-inch 1800R curved ultra-wide gaming display with Neo Quantum Processor Pro, 240Hz refresh rate, and 0.03ms GTG response.',
    specs: ['49" Dual QHD (5120x1440)', '240Hz Refresh Rate', '1800R Curved OLED', '0.03ms GTG Response', 'Samsung Gaming Hub'],
  },
  {
    _type: 'product',
    name: 'Apple Studio Display 27" 5K Retina',
    brand: 'Apple',
    category: 'monitors',
price: 899,
discountPrice: 949,
    imageUrl: '/images/monitors/apple_studio_display_5k.jpg',
    rating: 4.8,
    reviewsCount: 68,
    stock: 15,
    isFeatured: false,
    isNewRelease: false,
    description: '27-inch 5K Retina display with 12MP Ultra Wide camera with Center Stage, studio-quality mics, and six-speaker sound system with Spatial Audio.',
    specs: ['27" 5K Retina Display', '5120x2880 Resolution', '600 Nits Brightness', '12MP Ultra Wide Camera', '6-Speaker Spatial Audio', 'Thunderbolt 3 Up to 96W'],
  },
  {
    _type: 'product',
    name: 'LG UltraGear 34GS95QE 34" Curved OLED',
    brand: 'LG',
    category: 'monitors',
price: 749,
discountPrice: 799,
    imageUrl: '/images/monitors/lg_ultragear_34_curved.jpg',
    rating: 4.7,
    reviewsCount: 38,
    stock: 10,
    isFeatured: false,
    isNewRelease: true,
    description: '34-inch 800R curved WQHD OLED gaming monitor featuring 240Hz refresh rate, VESA DisplayHDR True Black 400, and NVIDIA G-SYNC compatibility.',
    specs: ['34" UltraWide WQHD (3440x1440)', '240Hz Refresh Rate', '800R Extreme Curve', 'VESA DisplayHDR True Black 400', 'NVIDIA G-SYNC & FreeSync'],
  },

  // GAMING ACCESSORIES ──────────────────────────────
  {
    _type: 'product',
    name: 'Razer Viper V3 Pro Wireless Gaming Mouse',
    brand: 'Razer',
    category: 'accessories',
    price: 159,
    discountPrice: 179,
    imageUrl: '/images/accessories/razer_viper_v3_pro.jpg',
    rating: 4.9,
    reviewsCount: 110,
    stock: 35,
    isFeatured: true,
    isNewRelease: true,
    description: 'Ultra-lightweight 54g esports wireless mouse with Focus Pro 35K Gen-2 Optical Sensor and 8000Hz HyperPolling rate.',
    specs: ['54g Ultra-Lightweight', 'Focus Pro 35K Optical Sensor', '8000Hz HyperPolling', '95 Hours Battery Life', 'Optical Mouse Switches Gen-3'],
  },
  {
    _type: 'product',
    name: 'Logitech G915 LIGHTSPEED Wireless Keyboard',
    brand: 'Logitech',
    category: 'accessories',
    price: 229,
    discountPrice: 249,
    imageUrl: '/images/accessories/logitech_g915_keyboard.jpg',
    rating: 4.8,
    reviewsCount: 95,
    stock: 25,
    isFeatured: false,
    isNewRelease: false,
    description: 'Low-profile mechanical switches, aircraft-grade aluminum top case, LIGHTSPEED 1ms wireless, and LIGHTSYNC RGB per-key lighting.',
    specs: ['Low Profile GL Tactile Switches', 'LIGHTSPEED 1ms Wireless', 'LIGHTSYNC RGB Per-Key', 'Aircraft-grade AL-MG Alloy', '30 Hours Battery Life'],
  },
  {
    _type: 'product',
    name: 'SteelSeries Arctis Nova Pro Wireless',
    brand: 'SteelSeries',
    category: 'accessories',
    price: 349,
    discountPrice: 379,
    imageUrl: '/images/accessories/steelseries_arctis_nova_pro.jpg',
    rating: 4.8,
    reviewsCount: 82,
    stock: 18,
    isFeatured: true,
    isNewRelease: false,
    description: 'High-Fidelity Drivers with 360° Spatial Audio, Active Noise Cancellation, wireless GameDAC Gen 2 base station, and dual battery hot-swap system.',
    specs: ['360° Spatial Audio', 'Active Noise Cancellation (ANC)', 'GameDAC Gen 2 Wireless Base', 'Dual-Battery Hot-Swap System', 'Simultaneous 2.4GHz + BT'],
  },
  {
    _type: 'product',
    name: 'Apple AirPods Max Space Black',
    brand: 'Apple',
    category: 'accessories',
    price: 549,
    discountPrice: 579,
    imageUrl: '/images/accessories/apple_airpods_max.jpg',
    rating: 4.9,
    reviewsCount: 145,
    stock: 20,
    isFeatured: false,
    isNewRelease: true,
    description: 'Apple-designed dynamic driver, Active Noise Cancellation with Transparency mode, Personalized Spatial Audio with dynamic head tracking.',
    specs: ['Apple-Designed Dynamic Driver', 'Active Noise Cancellation & Transparency', 'Personalized Spatial Audio', 'Digital Crown Control', 'USB-C Charging', '20 Hours Battery'],
  },

  // NETWORKING & STORAGE ──────────────────────────────
  {
    _type: 'product',
    name: 'ASUS ROG Rapture GT-BE98 PRO Wi-Fi 7 Router',
    brand: 'ASUS',
    category: 'networking',
    price: 799,
    discountPrice: 849,
    imageUrl: '/images/networking/asus_rog_rapture_wifi7.jpg',
    rating: 4.9,
    reviewsCount: 34,
    stock: 9,
    isFeatured: true,
    isNewRelease: true,
    description: 'Quad-band Wi-Fi 7 gaming router with up to 30,000 Mbps speeds, dual 10G ports, 320MHz channels, and multi-link operation (MLO).',
    specs: ['Quad-Band Wi-Fi 7 (Up to 30 Gbps)', 'Dual 10G Ports + Quad 2.5G Ports', '320MHz Channel Width', 'Triple-Level Game Acceleration', 'AiProtection Pro Security'],
  },
  {
    _type: 'product',
    name: 'Synology DiskStation DS923+ 4-Bay NAS',
    brand: 'Synology',
    category: 'networking',
    price: 599,
    discountPrice: 649,
    imageUrl: '/images/networking/synology_ds923_nas.jpg',
    rating: 4.8,
    reviewsCount: 61,
    stock: 14,
    isFeatured: false,
    isNewRelease: false,
    description: 'Flexible 4-bay storage solution for home offices and small business enterprises, supporting NVMe SSD caching and 10GbE network expansion.',
    specs: ['AMD Ryzen R1600 Dual-Core', '4 Bay (Expandable up to 9)', 'Dual M.2 NVMe SSD Slots', '4GB DDR4 ECC RAM', 'Synology DSM OS', '10GbE Network Slot'],
  },
  {
    _type: 'product',
    name: 'Ubiquiti UniFi Dream Machine Special Edition',
    brand: 'Ubiquiti',
    category: 'networking',
    price: 499,
    discountPrice: 549,
    imageUrl: '/images/networking/ubiquiti_unifi_udm_se.jpg',
    rating: 4.9,
    reviewsCount: 42,
    stock: 11,
    isFeatured: true,
    isNewRelease: false,
    description: 'All-in-one enterprise console with integrated 2.5G WAN, 8-port PoE switch, 10G SFP+ interfaces, and 128GB SSD storage for UniFi application suite.',
    specs: ['Integrated 8-Port PoE/PoE+ Switch', '2.5G RJ45 + 10G SFP+ Ports', 'Integrated 3.5" HDD Bay for NVR', '1.7 GHz Quad-Core CPU', 'UniFi OS Application Suite'],
  },

  // BUDGET TO PREMIUM — Full PKR Range (Rs. 100 → Rs. 300,000)
  // Prices stored as USD reference values (×279 = PKR)
  // ──────────────────────────────────────────────
  {
    _type: 'product',
    name: 'QuantumByte Tempered Glass Screen Protector (3-Pack)',
    brand: 'QuantumByte',
    category: 'mobiles',
    price: 0.36,
    discountPrice: 0.5,
    imageUrl: '/images/mobiles/screen-protector.jpg',
    rating: 4.6,
    reviewsCount: 312,
    stock: 200,
    isFeatured: false,
    isNewRelease: false,
    description: 'Ultra-thin 9H hardness tempered glass with oleophobic coating. Bubble-free installation kit included for all modern smartphones.',
    specs: ['9H Tempered Glass', 'Oleophobic Coating', '3-Pack with Applicator Kit', 'Full Curved Edge', 'Anti-Fingerprint'],
  },
  {
    _type: 'product',
    name: 'USB-C to USB-C Fast Charging Cable (1m)',
    brand: 'QuantumByte',
    category: 'chargers',
    price: 0.54,
    discountPrice: 0.72,
    imageUrl: '/images/chargers/usb-c-cable.jpg',
    rating: 4.7,
    reviewsCount: 245,
    stock: 150,
    isFeatured: false,
    isNewRelease: false,
    description: '60W PD-compatible braided USB-C cable with E-marker chip for reliable fast charging and data transfer up to 480Mbps.',
    specs: ['60W PD Fast Charging', 'Braided Nylon Jacket', 'E-Marker Chip', '1m Length', 'Data Sync Support'],
  },
  {
    _type: 'product',
    name: 'Silicone Shockproof Phone Case',
    brand: 'QuantumByte',
    category: 'mobiles',
    price: 0.9,
    discountPrice: 1.2,
    imageUrl: '/images/mobiles/phone-case.jpg',
    rating: 4.5,
    reviewsCount: 189,
    stock: 130,
    isFeatured: false,
    isNewRelease: false,
    description: 'Flexible liquid silicone case with raised camera lip and shock-absorbing corners. Precise cutouts for all ports and buttons.',
    specs: ['Liquid Silicone', 'Shock-Absorbing Corners', 'Raised Camera Lip', 'Anti-Slip Grip', 'Color-Matched Finish'],
  },
  {
    _type: 'product',
    name: 'Dual 3.5mm Gaming Earbuds',
    brand: 'QuantumByte',
    category: 'accessories',
    price: 1.43,
    discountPrice: 1.79,
    imageUrl: '/images/accessories/gaming-earbuds.jpg',
    rating: 4.4,
    reviewsCount: 156,
    stock: 90,
    isFeatured: false,
    isNewRelease: false,
    description: 'Lightweight in-ear gaming buds with in-line mic and enhanced bass drivers. Perfect for mobile and PC gaming.',
    specs: ['10mm Bass Drivers', 'In-Line Mic', '3.5mm Jack', 'Memory Foam Tips', 'Tangle-Free Cable'],
  },
  {
    _type: 'product',
    name: '64GB USB 3.0 Flash Drive',
    brand: 'QuantumByte',
    category: 'parts',
    price: 2.15,
    discountPrice: 2.87,
    imageUrl: '/images/parts/flash-drive.jpg',
    rating: 4.6,
    reviewsCount: 420,
    stock: 180,
    isFeatured: false,
    isNewRelease: false,
    description: 'Pocket-sized metal-body USB 3.0 drive with read speeds up to 130MB/s. Keychain loop included.',
    specs: ['64GB Capacity', 'USB 3.0 (Up to 130MB/s)', 'Metal Body', 'Keychain Loop', 'Plug & Play'],
  },
  {
    _type: 'product',
    name: 'Extended RGB Gaming Mouse Pad',
    brand: 'QuantumByte',
    category: 'accessories',
    price: 2.87,
    discountPrice: 3.58,
    imageUrl: '/images/accessories/mouse-pad.jpg',
    rating: 4.7,
    reviewsCount: 233,
    stock: 110,
    isFeatured: false,
    isNewRelease: false,
    description: '900x400mm cloth desk pad with stitched edges, non-slip rubber base, and a full-color RGB light loop around the edge.',
    specs: ['900x400mm Size', 'Stitched Edges', 'Non-Slip Rubber Base', 'RGB Edge Lighting', 'Waterproof Surface'],
  },
  {
    _type: 'product',
    name: 'Wired Mechanical Gaming Keyboard (87-Key)',
    brand: 'QuantumByte',
    category: 'accessories',
    price: 3.58,
    discountPrice: 4.48,
    imageUrl: '/images/accessories/keyboard.jpg',
    rating: 4.6,
    reviewsCount: 168,
    stock: 80,
    isFeatured: false,
    isNewRelease: false,
    description: 'Hot-swappable red switches, per-key RGB, full-key rollover, and a compact TKL layout for maximum desk space.',
    specs: ['Hot-Swappable Red Switches', 'Per-Key RGB', 'TKL Layout', 'Full-Key Rollover', 'Detachable USB-C'],
  },
  {
    _type: 'product',
    name: '65W GaN Dual-Port Fast Charger',
    brand: 'QuantumByte',
    category: 'chargers',
    price: 5.38,
    discountPrice: 6.45,
    imageUrl: '/images/chargers/usb-charger.jpg',
    rating: 4.7,
    reviewsCount: 290,
    stock: 120,
    isFeatured: false,
    isNewRelease: true,
    description: 'Gallium Nitride technology delivers 65W from two USB-C ports in a tiny footprint. Charges laptops, phones, and tablets.',
    specs: ['65W Max Output', '2x USB-C PD 3.0', 'GaN Technology', 'Compact Folding Pins', 'Over-Voltage Protection'],
  },
  {
    _type: 'product',
    name: '120mm RGB Case Fan 3-Pack',
    brand: 'QuantumByte',
    category: 'parts',
    price: 7.17,
    discountPrice: 8.96,
    imageUrl: '/images/parts/case-fan.jpg',
    rating: 4.5,
    reviewsCount: 143,
    stock: 95,
    isFeatured: false,
    isNewRelease: false,
    description: 'High static-pressure ARGB fans with PWM control and daisy-chain connectors for clean, quiet case cooling.',
    specs: ['120mm ARGB Fans', 'PWM Speed Control', 'Daisy-Chain Connectors', 'Hydraulic Bearings', '3-Pack with Hub'],
  },
  {
    _type: 'product',
    name: '240GB SATA III SSD',
    brand: 'QuantumByte',
    category: 'parts',
    price: 10.75,
    discountPrice: 12.54,
    imageUrl: '/images/parts/sata-ssd.jpg',
    rating: 4.6,
    reviewsCount: 378,
    stock: 100,
    isFeatured: false,
    isNewRelease: false,
    description: 'Entry-level solid state upgrade for old laptops and desktops. Read speeds up to 550MB/s, silent and shock-resistant.',
    specs: ['240GB Capacity', 'Up to 550MB/s Read', 'SATA III Interface', 'TRIM Support', '3-Year Warranty'],
  },
  {
    _type: 'product',
    name: '16000 DPI Wired Gaming Mouse',
    brand: 'QuantumByte',
    category: 'accessories',
    price: 10.75,
    discountPrice: 12.9,
    imageUrl: '/images/accessories/gaming-mouse.jpg',
    rating: 4.7,
    reviewsCount: 205,
    stock: 85,
    isFeatured: false,
    isNewRelease: false,
    description: 'Ergonomic gaming mouse with 16000 DPI optical sensor, 7 programmable buttons, and customizable RGB lighting.',
    specs: ['16000 DPI Sensor', '7 Programmable Buttons', 'RGB Lighting', 'Ergonomic Grip', 'Braided USB Cable'],
  },
  {
    _type: 'product',
    name: 'True Wireless Earbuds with Charging Case',
    brand: 'QuantumByte',
    category: 'accessories',
    price: 14.34,
    discountPrice: 17.92,
    imageUrl: '/images/accessories/tws-earbuds.jpg',
    rating: 4.5,
    reviewsCount: 176,
    stock: 75,
    isFeatured: false,
    isNewRelease: true,
    description: 'Bluetooth 5.3 TWS earbuds with touch controls, ENC mic, and 24-hour total battery life with the charging case.',
    specs: ['Bluetooth 5.3', 'Touch Controls', 'ENC Microphone', '24H Total Battery', 'IPX4 Water Resistant'],
  },
  {
    _type: 'product',
    name: '500GB NVMe M.2 SSD',
    brand: 'QuantumByte',
    category: 'parts',
    price: 16.13,
    discountPrice: 19.35,
    imageUrl: '/images/parts/nvme-ssd.jpg',
    rating: 4.8,
    reviewsCount: 262,
    stock: 90,
    isFeatured: false,
    isNewRelease: true,
    description: 'PCIe 3.0 NVMe performance up to 3,500MB/s read — a massive speed jump over SATA drives for games and OS.',
    specs: ['500GB Capacity', 'Up to 3,500MB/s Read', 'PCIe 3.0 x4 NVMe', 'M.2 2280 Form Factor', '5-Year Warranty'],
  },
  {
    _type: 'product',
    name: '1080p HD Webcam with Mic',
    brand: 'QuantumByte',
    category: 'accessories',
    price: 21.51,
    discountPrice: 25.09,
    imageUrl: '/images/accessories/steelseries_arctis_nova_pro.jpg',
    rating: 4.4,
    reviewsCount: 121,
    stock: 60,
    isFeatured: false,
    isNewRelease: false,
    description: 'Full HD 1080p webcam with dual noise-reducing mics, privacy shutter, and universal clip for streaming and meetings.',
    specs: ['1080p Full HD', 'Dual Noise-Reducing Mics', 'Privacy Shutter', 'Universal Clip', 'Plug & Play USB'],
  },
  {
    _type: 'product',
    name: '1TB External Portable HDD',
    brand: 'QuantumByte',
    category: 'parts',
    price: 28.67,
    discountPrice: 32.26,
    imageUrl: '/images/parts/samsung_990_pro_ssd.jpg',
    rating: 4.6,
    reviewsCount: 194,
    stock: 70,
    isFeatured: false,
    isNewRelease: false,
    description: 'Compact USB 3.0 external drive with drop protection and automatic backup software. Ideal for photos, videos, and docs.',
    specs: ['1TB Capacity', 'USB 3.0 (Up to 120MB/s)', 'Shock-Resistant Shell', 'Auto Backup Software', 'Plug & Play'],
  },
  {
    _type: 'product',
    name: '24" 100Hz IPS FHD Monitor',
    brand: 'QuantumByte',
    category: 'monitors',
    price: 53.76,
    discountPrice: 64.52,
    imageUrl: '/images/monitors/lg_ultragear_34_curved.jpg',
    rating: 4.6,
    reviewsCount: 88,
    stock: 40,
    isFeatured: false,
    isNewRelease: true,
    description: 'Slim-bezel 1080p IPS panel with 100Hz refresh rate, FreeSync support, and low blue light mode for all-day comfort.',
    specs: ['24" FHD IPS', '100Hz Refresh Rate', 'AMD FreeSync', 'HDMI + VGA Ports', 'Low Blue Light'],
  },
  {
    _type: 'product',
    name: '27" 144Hz QHD Gaming Monitor',
    brand: 'QuantumByte',
    category: 'monitors',
    price: 89.61,
    discountPrice: 107.53,
    imageUrl: '/images/monitors/asus_rog_swift_4k_oled.jpg',
    rating: 4.7,
    reviewsCount: 64,
    stock: 30,
    isFeatured: false,
    isNewRelease: true,
    description: 'WQHD 2560x1440 IPS panel with 144Hz refresh, 1ms response, HDR400, and an ergonomic height-adjustable stand.',
    specs: ['27" QHD (2560x1440)', '144Hz + 1ms', 'IPS Panel', 'HDR400', 'HDMI 2.0 + DisplayPort'],
  },
  {
    _type: 'product',
    name: '512GB NVMe M.2 SSD',
    brand: 'QuantumByte',
    category: 'parts',
    price: 25.09,
    discountPrice: 28.67,
    imageUrl: '/images/parts/samsung_990_pro_ssd.jpg',
    rating: 4.8,
    reviewsCount: 231,
    stock: 85,
    isFeatured: false,
    isNewRelease: false,
    description: 'PCIe 4.0 NVMe speed up to 5,000MB/s read with a slim graphene heatsink for sustained performance.',
    specs: ['512GB Capacity', 'Up to 5,000MB/s Read', 'PCIe 4.0 x4 NVMe', 'Graphene Heatsink', '5-Year Warranty'],
  },
  {
    _type: 'product',
    name: '2TB External Portable HDD',
    brand: 'QuantumByte',
    category: 'parts',
    price: 43.01,
    discountPrice: 50.18,
    imageUrl: '/images/parts/samsung_990_pro_ssd.jpg',
    rating: 4.7,
    reviewsCount: 152,
    stock: 55,
    isFeatured: false,
    isNewRelease: false,
    description: 'Double the storage for gamers and creators. USB 3.0 portable drive with rugged sleeve and backup software.',
    specs: ['2TB Capacity', 'USB 3.0 (Up to 120MB/s)', 'Rugged Sleeve Included', 'Auto Backup Software', 'Drop Protection'],
  },
  {
    _type: 'product',
    name: 'RTX 4060 8GB Graphics Card',
    brand: 'NVIDIA',
    category: 'parts',
    price: 215.05,
    discountPrice: 232.97,
    imageUrl: '/images/parts/nvidia_rtx_4090_gpu.jpg',
    rating: 4.7,
    reviewsCount: 96,
    stock: 20,
    isFeatured: true,
    isNewRelease: false,
    description: 'Ada Lovelace GPU with DLSS 3, ray tracing, and efficient 115W TDP. The sweet spot for 1080p high-refresh gaming.',
    specs: ['RTX 4060 8GB GDDR6', 'DLSS 3 + Ray Tracing', '115W TDP', '2-Fan Compact Design', 'PCIe 4.0'],
  },
  {
    _type: 'product',
    name: '1440p 165Hz UltraGear Gaming Monitor',
    brand: 'LG',
    category: 'monitors',
    price: 161.29,
    discountPrice: 179.21,
    imageUrl: '/images/monitors/lg_ultragear_34_curved.jpg',
    rating: 4.8,
    reviewsCount: 72,
    stock: 25,
    isFeatured: true,
    isNewRelease: true,
    description: 'Fast IPS 27-inch QHD panel with 165Hz refresh, 1ms GTG, G-Sync compatible, and DisplayHDR 400 certification.',
    specs: ['27" QHD Fast IPS', '165Hz + 1ms GTG', 'G-Sync Compatible', 'DisplayHDR 400', 'HDMI 2.0 x2 + DP 1.4'],
  },
  {
    _type: 'product',
    name: 'Intel Core i5-14400F + RTX 4060 Gaming PC',
    brand: 'QuantumByte',
    category: 'computers',
    price: 286.74,
    discountPrice: 322.58,
    imageUrl: '/images/computers/asus_rog_strix_g35.jpg',
    rating: 4.7,
    reviewsCount: 41,
    stock: 12,
    isFeatured: true,
    isNewRelease: true,
    description: 'Entry-level 1080p gaming beast: Core i5-14400F, RTX 4060, 16GB DDR5, and 1TB NVMe in a clean mid-tower.',
    specs: ['Intel Core i5-14400F', 'NVIDIA RTX 4060 8GB', '16GB DDR5 RAM', '1TB NVMe SSD', '650W Bronze PSU'],
  },
  {
    _type: 'product',
    name: 'RTX 4070 12GB Graphics Card',
    brand: 'NVIDIA',
    category: 'parts',
    price: 143.37,
    discountPrice: 161.29,
    imageUrl: '/images/parts/nvidia_rtx_4090_gpu.jpg',
    rating: 4.8,
    reviewsCount: 87,
    stock: 18,
    isFeatured: true,
    isNewRelease: false,
    description: 'Rock-solid 1440p high-refresh performer with DLSS 3.5, 12GB VRAM, and excellent efficiency at 200W.',
    specs: ['RTX 4070 12GB GDDR6X', 'DLSS 3.5 + Ray Tracing', '200W TDP', '3-Fan Premium Cooler', 'PCIe 4.0'],
  },
  {
    _type: 'product',
    name: '4K QD-OLED 240Hz Gaming Monitor',
    brand: 'QuantumByte',
    category: 'monitors',
    price: 430.11,
    discountPrice: 466.49,
    imageUrl: '/images/monitors/asus_rog_swift_4k_oled.jpg',
    rating: 4.9,
    reviewsCount: 33,
    stock: 10,
    isFeatured: true,
    isNewRelease: true,
    description: 'Stunning 4K QD-OLED panel with 240Hz refresh, 0.03ms response, and true black levels for the ultimate gaming picture.',
    specs: ['32" 4K QD-OLED', '240Hz Refresh Rate', '0.03ms Response', 'DisplayHDR True Black 400', 'USB-C 90W'],
  },
  {
    _type: 'product',
    name: 'Gaming Laptop RTX 4060 | 16GB | 512GB',
    brand: 'QuantumByte',
    category: 'laptops',
    price: 537.63,
    discountPrice: 573.48,
    imageUrl: '/images/laptops/asus_rog_zephyrus_g16.jpg',
    rating: 4.7,
    reviewsCount: 58,
    stock: 15,
    isFeatured: true,
    isNewRelease: false,
    description: '16-inch 165Hz laptop with Core i7, RTX 4060, 16GB DDR5, and 512GB NVMe — a balanced on-the-go gaming rig.',
    specs: ['Intel Core i7-13620H', 'NVIDIA RTX 4060 8GB', '16GB DDR5', '512GB NVMe SSD', '16" 165Hz FHD'],
  },
  {
    _type: 'product',
    name: 'Ryzen 7 7800X3D + RTX 4070 Super Build',
    brand: 'QuantumByte',
    category: 'computers',
    price: 716.85,
    discountPrice: 787.53,
    imageUrl: '/images/computers/hp_omen_45l.jpg',
    rating: 4.9,
    reviewsCount: 27,
    stock: 8,
    isFeatured: true,
    isNewRelease: true,
    description: 'The esports dream machine: 3D V-Cache CPU, RTX 4070 Super, 32GB DDR5, and 2TB NVMe with liquid cooling.',
    specs: ['AMD Ryzen 7 7800X3D', 'NVIDIA RTX 4070 Super 12GB', '32GB DDR5 6000MHz', '2TB NVMe SSD', '360mm AIO Cooler'],
  },
  {
    _type: 'product',
    name: 'Intel Core i7-14700F + RTX 4070 Ti Super Build',
    brand: 'QuantumByte',
    category: 'computers',
    price: 896.06,
    discountPrice: 985.66,
    imageUrl: '/images/computers/alienware_aurora_r16.jpg',
    rating: 4.8,
    reviewsCount: 19,
    stock: 6,
    isFeatured: true,
    isNewRelease: true,
    description: '4K-ready powerhouse: Core i7, RTX 4070 Ti Super, 32GB DDR5, and 2TB Gen4 NVMe for creators and streamers.',
    specs: ['Intel Core i7-14700F', 'NVIDIA RTX 4070 Ti Super 16GB', '32GB DDR5', '2TB Gen4 NVMe SSD', '850W Gold PSU'],
  },
  {
    _type: 'product',
    name: 'Ultimate Creator Workstation i9 + RTX 4090',
    brand: 'QuantumByte',
    category: 'computers',
    price: 1075.27,
    discountPrice: 1146.95,
    imageUrl: '/images/computers/quantumbyte_custom_rig.jpg',
    rating: 5.0,
    reviewsCount: 14,
    stock: 4,
    isFeatured: true,
    isNewRelease: true,
    description: 'The flagship: Core i9-14900K, RTX 4090, 64GB DDR5, 4TB NVMe, and custom liquid cooling for uncompromising performance.',
    specs: ['Intel Core i9-14900K', 'NVIDIA RTX 4090 24GB', '64GB DDR5 6400MHz', '4TB Gen5 NVMe SSD', 'Custom Loop Liquid Cooling'],
  },
]

// ─────────────────────────────────────────────────────────
// IT SERVICES DATA
// ─────────────────────────────────────────────────────────
const itServices = [
  {
    _type: 'itService',
    title: 'Custom Gaming & Workstation PC Assembly',
    subtitle: 'Professional assembly, custom liquid loop tubing, cable management & stress testing',
    imageUrl: '/images/services/custom_pc_building.jpg',
    priceStarting: 99,
    popularBadge: true,
    features: [
      'Handcrafted Component Installation & Cable Routing',
      'BIOS Flashing & XMP/EXPO Memory Tuning',
      'Stress Testing & Thermal Benchmarking (24 Hours)',
      'Custom Hardline or Softline Water Cooling Loops',
      'Official QuantumByte 1-Year Build Warranty',
    ],
    description: 'Our expert hardware engineers build your dream rig with surgical precision, immaculate cable routing, and optimal airflow.',
  },
  {
    _type: 'itService',
    title: 'Hardware Maintenance & Chip-Level Repair',
    subtitle: 'Diagnose and fix laptops, desktops, GPUs, motherboards & mobile devices',
    imageUrl: '/images/services/hardware_repair.jpg',
    priceStarting: 49,
    popularBadge: false,
    features: [
      'Motherboard BGA Reballing & Micro-soldering',
      'Laptop Screen, Battery & Keyboard Replacement',
      'Liquid Damage Cleaning & Ultrasonic Bathing',
      'GPU Thermal Paste & Pad Replacement (Honeywell PTM7950)',
      'Component-level Short Circuit Diagnostics',
    ],
    description: 'Our lab uses advanced diagnostic scopes to repair micro-electronics and save your valuable hardware from the bin.',
  },
  {
    _type: 'itService',
    title: 'Corporate IT Infrastructure & Networking',
    subtitle: 'Enterprise server setup, Wi-Fi 6E mesh coverage, NAS storage & security',
    imageUrl: '/images/services/network_infrastructure.jpg',
    priceStarting: 299,
    popularBadge: true,
    features: [
      'Structured Cat6A / Fiber Optic Cabling',
      'Synology / QNAP Enterprise NAS Backup Systems',
      'Cisco / Ubiquiti UniFi Router & Firewall Setup',
      'Active Directory, VPN & Cloud Migration',
      '24/7 Managed IT Support & SLA Contracts',
    ],
    description: 'Scale your infrastructure with secure, high-speed networking solutions designed for zero downtime and robust data backup.',
  },
  {
    _type: 'itService',
    title: 'Full-Stack Web & Mobile App Development',
    subtitle: 'Custom e-commerce platforms, SaaS web apps, iOS & Android applications',
    imageUrl: '/images/services/software_web_dev.jpg',
    priceStarting: 799,
    popularBadge: false,
    features: [
      'Modern Next.js 16, React, & Node.js Applications',
      'Sanity CMS & Headless Backend Architecture',
      'Stripe, PayPal & Custom Payment Gateway Integration',
      'UI/UX Design with GSAP Motion & Micro-interactions',
      'SEO Optimization & 99+ Lighthouse Speed Score',
    ],
    description: 'Transform your digital vision into high-converting, lightning-fast web applications built by senior engineering teams.',
  },
]

// ─────────────────────────────────────────────────────────
// RUN SEEDING
// ─────────────────────────────────────────────────────────
async function deleteExisting(type) {
  console.log(`🗑️  Deleting existing ${type} documents...`)
  const existing = await client.fetch(`*[_type == "${type}"]._id`)
  if (existing.length > 0) {
    const transaction = client.transaction()
    existing.forEach(id => transaction.delete(id))
    await transaction.commit()
    console.log(`   Deleted ${existing.length} existing ${type} documents.`)
  }
}

async function seedDocuments(docs, label) {
  console.log(`\n📦 Seeding ${docs.length} ${label}...`)
  let count = 0
  for (const doc of docs) {
    await client.create(doc)
    count++
    process.stdout.write(`   ✓ ${count}/${docs.length} — ${doc.name || doc.title}\n`)
  }
}

async function main() {
  console.log('\n🚀 QuantumByte Technologies — Sanity Seed Script')
  console.log(`   Project: ${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}`)
  console.log(`   Dataset: ${process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'}\n`)

  await deleteExisting('product')
  await deleteExisting('itService')

  await seedDocuments(products, 'products')
  await seedDocuments(itServices, 'IT services')

  console.log(`\n✅ Seeding complete! ${products.length} products + ${itServices.length} IT services added to Sanity.`)
  console.log('   Visit your Sanity Studio at http://localhost:3000/studio to verify.\n')
}

main().catch(err => {
  console.error('\n❌ Seed failed:', err.message)
  process.exit(1)
})
